import React, { useState, useEffect } from 'react';
import { FollowUp, Lead, UserProfile } from '../../types'; // Assuming FollowUp type is available
import { SelectField } from '../ui/SelectField'; // Import SelectField

// Define the shape of the data the onSubmit function will receive
// Excludes fields auto-generated by DB (id, created_at, updated_at) or joined data (leads, users)
export interface NewFollowUpData {
  lead_id: string;
  agent_id: string;
  due_date: string; // ISO string
  status: 'Pending' | 'Completed' | 'Rescheduled' | 'Cancelled';
  notes?: string;
}

interface CreateFollowUpModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (followUpData: NewFollowUpData) => void;
  leads: Lead[]; 
  agents: UserProfile[];
  isLoadingLeads?: boolean;
  isLoadingAgents?: boolean;
}

const CreateFollowUpModal: React.FC<CreateFollowUpModalProps> = ({
  isOpen,
  onClose,
  onSubmit,
  leads,
  agents,
  isLoadingLeads,
  isLoadingAgents,
}) => {
  const [leadId, setLeadId] = useState('');
  const [agentId, setAgentId] = useState('');
  const [dueDate, setDueDate] = useState('');
  const [status, setStatus] = useState<FollowUp['status']>('Pending');
  const [notes, setNotes] = useState('');

  useEffect(() => {
    if (isOpen) {
      // Reset form when modal opens
      const today = new Date();
      today.setDate(today.getDate() + 1); // Default to tomorrow
      setDueDate(today.toISOString().split('T')[0]);
      setLeadId('');
      setAgentId('');
      setStatus('Pending');
      setNotes('');
    }
  }, [isOpen]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!leadId || !agentId || !dueDate) {
      alert('Please fill in all required fields: Lead, Agent, and Due Date.');
      return;
    }
    
    onSubmit({
      lead_id: leadId,
      agent_id: agentId,
      due_date: new Date(dueDate).toISOString(),
      status,
      notes: notes || undefined,
    });
  };

  if (!isOpen) return null;

  const leadOptions = [
    { value: '', label: 'Select Lead' },
    ...(leads?.map(lead => ({
      value: lead.id,
      label: `${lead.clients?.client_name || lead.contact_person || 'Unnamed Lead'} (ID: ${lead.id.substring(0, 8)}...)`
    })) || [])
  ];

  const agentOptions = [
    { value: '', label: 'Select Agent' },
    ...(agents?.map(agent => ({
      value: agent.id,
      label: agent.full_name || agent.email || 'Unnamed Agent'
    })) || [])
  ];

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50 transition-opacity duration-300 ease-in-out">
      <div className="bg-white rounded-lg shadow-xl p-6 w-full max-w-lg max-h-[90vh] overflow-y-auto">
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-xl font-semibold text-gray-800">Create New Follow-Up</h2>
          <button onClick={onClose} className="text-gray-500 hover:text-gray-700 text-2xl">&times;</button>
        </div>
        <form onSubmit={handleSubmit} className="space-y-4">
          <SelectField
            id="followup-leadId"
            label="Lead"
            value={leadId}
            onChange={(e: React.ChangeEvent<HTMLSelectElement>) => setLeadId(e.target.value)}
            options={leadOptions}
            isLoading={isLoadingLeads}
            required
            // No register or error props needed for simple controlled SelectField
            // Add className if needed for styling consistency
          />
          <SelectField
            id="followup-agentId"
            label="Agent"
            value={agentId}
            onChange={(e: React.ChangeEvent<HTMLSelectElement>) => setAgentId(e.target.value)}
            options={agentOptions}
            isLoading={isLoadingAgents}
            required
            // No register or error props needed for simple controlled SelectField
          />
          <div>
            <label htmlFor="followup-dueDate" className="block text-sm font-medium text-gray-700">Due Date <span className="text-red-500">*</span></label>
            <input
              type="date"
              id="followup-dueDate"
              value={dueDate}
              onChange={(e) => setDueDate(e.target.value)}
              className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              required
            />
          </div>
          <div>
            <label htmlFor="followup-status" className="block text-sm font-medium text-gray-700">Status</label>
            <select
              id="followup-status"
              value={status}
              onChange={(e) => setStatus(e.target.value as FollowUp['status'])}
              className="mt-1 block w-full px-3 py-2 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
            >
              <option value="Pending">Pending</option>
              <option value="Completed">Completed</option>
              <option value="Rescheduled">Rescheduled</option>
              <option value="Cancelled">Cancelled</option>
            </select>
          </div>
          <div>
            <label htmlFor="followup-notes" className="block text-sm font-medium text-gray-700">Notes (Optional)</label>
            <textarea
              id="followup-notes"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
            />
          </div>
          <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
              Create Follow-Up
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateFollowUpModal; 