// src/types/index.ts

// User profile structure (mirroring AuthContext and public.users)
export interface UserProfile {
  id: string;
  email?: string;
  role?: 'agent' | 'manager' | 'super_admin';
  full_name?: string;
  manager_id?: string | null;
  // other fields from your public.users table
}

// Client structure (mirroring public.clients)
export interface Client {
  id: string;
  client_name: string;
  company?: string | null;
  industry?: string | null;
  location?: string | null;
  phone?: string | null;
  physical_meeting_info?: string | null;
  expected_value?: number | null;
  created_at: string;
  updated_at: string;
  company_size?: number | null;
  email?: string | null;
}

// Lead engagement structure (mirroring public.leads and joined data)
export interface Lead {
  id: string;
  client_id: string;
  agent_id: string | null;
  status_bucket: 'P1' | 'P2' | 'P3';
  progress_details?: string | null;
  next_step?: string | null;
  sync_lock?: boolean | null;
  created_at: string;
  updated_at: string;
  clients?: {
    client_name: string;
    company?: string | null;
    company_size?: number | null;
  } | null;
  users?: Pick<UserProfile, 'full_name'> | null;
  lead_source?: string | null;
  contact_person?: string | null;
  email?: string | null;
  phone?: string | null;
  deal_value?: number | null;
  tags?: string[] | null;
  follow_up_due_date?: string | null;
}

// You can add more types here as needed for FollowUps, Meetings etc.
export interface FollowUp {
  id: string;
  lead_id: string;
  agent_id: string;
  due_date: string;
  status: 'Pending' | 'Completed' | 'Rescheduled' | 'Cancelled';
  notes?: string | null;
  created_at: string;
  updated_at: string;
  leads?: Lead | null; // Optional joined lead data
  users?: Pick<UserProfile, 'full_name'> | null; // Optional joined agent data
}

export interface Meeting {
  id: string;
  lead_id: string | null;
  agent_id: string;
  title: string;
  start_time: string;
  end_time: string;
  status: 'Scheduled' | 'Completed' | 'Pending' | 'Cancelled';
  location?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  leads?: Lead | null; // Optional joined lead data
  users?: Pick<UserProfile, 'full_name'> | null; // Optional joined agent data
}

// --- Daily Report Types ---
export type TeamType = 'telesales' | 'linkedin' | 'cold_email';

export interface BaseDailyReport {
  id?: string; // UUID, generated by DB
  agent_id: string;
  manager_id: string | null; // Should be derived from agent's profile
  report_date: string; // YYYY-MM-DD
  team_type: TeamType;
  created_at?: string; // Timestamp
  updated_at?: string; // Timestamp
}

export interface TelesalesDailyReport extends BaseDailyReport {
  team_type: 'telesales';
  outreach_count: number;
  responses_count: number;
}

export interface LinkedInDailyReport extends BaseDailyReport {
  team_type: 'linkedin';
  outreach_count: number;
  responses_count: number;
  comments_done: number;
  content_posted: boolean;
}

export interface ColdEmailDailyReport extends BaseDailyReport {
  team_type: 'cold_email';
  emails_sent: number;
  responses_count: number;
}

export type DailyReport = TelesalesDailyReport | LinkedInDailyReport | ColdEmailDailyReport;
// --- End Daily Report Types ---

// --- Attendance Types ---
export type AttendanceStatus = 'CheckedOut' | 'CheckedIn' | 'OnLeave';

export interface Attendance {
  id: string; // UUID
  user_id: string; // FK to users.id
  check_in_time: string | null; // ISO Timestamp
  check_out_time: string | null; // ISO Timestamp
  date: string; // YYYY-MM-DD
  status: AttendanceStatus;
  notes: string | null;
  created_at: string; // ISO Timestamp
  updated_at: string; // ISO Timestamp

  // Optional joined data for display
  users?: Pick<UserProfile, 'full_name' | 'email'> | null; 
}
// --- End Attendance Types --- 